
project_id = "vkftjzirmhsyvtodxzxa"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-payment-session]
verify_jwt = true

[functions.nexi-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.verify-lock-code]
verify_jwt = false
