-- Insert test products
INSERT INTO public.predmeti (naziv, naziv_en, naziv_de, naziv_it, naziv_ru, koda, stevilka, barva, opis, opis_en, opis_de, opis_it, opis_ru, slika_url, slike_urls, cena, zaloga, na_voljo, kategorija_id, atributi, status, popust, seo_slug) VALUES
(
  'Elegantna črna jakna', 
  'Elegant Black Jacket', 
  'Elegante schwarze Jacke', 
  'Giacca nera elegante', 
  'Элегантная чёрная куртка',
  'JAK001', 
  'J-2024-001', 
  'črna', 
  'Kakovostna črna jakna iz pravega usnja, primerna za poslovno in priložnostno nošenje.',
  'High-quality black leather jacket, suitable for business and casual wear.',
  'Hochwertige schwarze Lederjacke, geeignet für Business und Freizeit.',
  'Giacca di pelle nera di alta qualità, adatta per uso professionale e casual.',
  'Высококачественная чёрная кожаная куртка, подходящая для делового и повседневного ношения.',
  'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
  ARRAY['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500', 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500', 'https://images.unsplash.com/photo-1606208964162-b6b4ea3f4bdc?w=500'],
  129.99, 
  5, 
  true, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Oblačila' LIMIT 1),
  '{"material": "pravo usnje", "velikost": "M", "znamka": "Unknown", "letnik": "2024", "javni_atributi": ["material", "velikost", "znamka"]}',
  'novo',
  0,
  'elegantna-crna-jakna-jak001'
),
(
  'Samsung Galaxy S22', 
  'Samsung Galaxy S22', 
  'Samsung Galaxy S22', 
  'Samsung Galaxy S22', 
  'Samsung Galaxy S22',
  'TEL001', 
  'SGS22-001', 
  'črna', 
  'Zmogljiv pametni telefon z odlično kamero in dolgoživo baterijo.',
  'Powerful smartphone with excellent camera and long-lasting battery.',
  'Leistungsstarkes Smartphone mit ausgezeichneter Kamera und langlebigem Akku.',
  'Smartphone potente con fotocamera eccellente e batteria a lunga durata.',
  'Мощный смартфон с отличной камерой и долговечной батареей.',
  'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',
  ARRAY['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500', 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500', 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=500'],
  699.99, 
  3, 
  true, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Elektronika' LIMIT 1),
  '{"pomnilnik": "128GB", "ram": "8GB", "barva_ohisja": "črna", "garancija": "2 leti", "javni_atributi": ["pomnilnik", "ram", "garancija"]}',
  'znizano',
  15,
  'samsung-galaxy-s22-tel001'
),
(
  'Rolex Daytona replika', 
  'Rolex Daytona Replica', 
  'Rolex Daytona Nachbau', 
  'Replica Rolex Daytona', 
  'Реплика Rolex Daytona',
  'URA001', 
  'RD-REP-001', 
  'zlata', 
  'Visokokakovostna replika znamenite Rolex Daytona ure z avtomatskim mehanizmom.',
  'High-quality replica of the famous Rolex Daytona watch with automatic mechanism.',
  'Hochwertige Nachbildung der berühmten Rolex Daytona Uhr mit automatischem Uhrwerk.',
  'Replica di alta qualità del famoso orologio Rolex Daytona con meccanismo automatico.',
  'Высококачественная реплика знаменитых часов Rolex Daytona с автоматическим механизмом.',
  'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500',
  ARRAY['https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500', 'https://images.unsplash.com/photo-1606859490609-1816b4ebc38b?w=500'],
  89.99, 
  2, 
  true, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Nakit' LIMIT 1),
  '{"material": "nerjavno jeklo", "mehanizem": "avtomatski", "voda_odporno": "50m", "premer": "40mm", "javni_atributi": ["material", "mehanizem", "voda_odporno"]}',
  'novo',
  0,
  'rolex-daytona-replika-ura001'
),
(
  'Dyson V11 sesalnik', 
  'Dyson V11 Vacuum', 
  'Dyson V11 Staubsauger', 
  'Aspirapolvere Dyson V11', 
  'Пылесос Dyson V11',
  'SES001', 
  'DV11-001', 
  'modra', 
  'Brezžični sesalnik z močnim sesanjem in dolgotrajno baterijo.',
  'Cordless vacuum cleaner with powerful suction and long-lasting battery.',
  'Kabelloser Staubsauger mit starker Saugkraft und langlebigem Akku.',
  'Aspirapolvere senza fili con aspirazione potente e batteria a lunga durata.',
  'Беспроводной пылесос с мощным всасыванием и долговечной батареей.',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
  ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500', 'https://images.unsplash.com/photo-1567722552798-e3f46c5a8b90?w=500'],
  399.99, 
  0, 
  false, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Oprema za dom' LIMIT 1),
  '{"moc": "545W", "cas_delovanja": "60min", "volumen_posode": "0.76L", "tip": "brezžični", "javni_atributi": ["moc", "cas_delovanja", "tip"]}',
  'prodano',
  0,
  'dyson-v11-sesalnik-ses001'
),
(
  'Abstraktna slika "Sončni zahod"', 
  'Abstract Painting "Sunset"', 
  'Abstraktes Gemälde "Sonnenuntergang"', 
  'Dipinto astratto "Tramonto"', 
  'Абстрактная картина "Закат"',
  'UME001', 
  'AS-2023-001', 
  'večbarvna', 
  'Originalna abstraktna slika na platnu, ustvarjena z oljnimi barvami.',
  'Original abstract painting on canvas, created with oil paints.',
  'Originales abstraktes Gemälde auf Leinwand, mit Ölfarben erstellt.',
  'Dipinto astratto originale su tela, creato con colori ad olio.',
  'Оригинальная абстрактная картина на холсте, выполненная масляными красками.',
  'https://images.unsplash.com/photo-1549490349-8643362247b5?w=500',
  ARRAY['https://images.unsplash.com/photo-1549490349-8643362247b5?w=500', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500'],
  250.00, 
  1, 
  true, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Umetnost' LIMIT 1),
  '{"velikost": "60x80cm", "material": "olje na platnu", "avtor": "neznan", "leto": "2023", "okvirjena": "da", "javni_atributi": ["velikost", "material", "leto", "okvirjena"]}',
  'znizano',
  20,
  'abstraktna-slika-soncni-zahod-ume001'
),
(
  'MacBook Pro 13"', 
  'MacBook Pro 13"', 
  'MacBook Pro 13"', 
  'MacBook Pro 13"', 
  'MacBook Pro 13"',
  'LAP001', 
  'MBP13-001', 
  'siva', 
  'Rabljen MacBook Pro 13" v odličnem stanju, primeren za delo in študij.',
  'Used MacBook Pro 13" in excellent condition, suitable for work and study.',
  'Gebrauchtes MacBook Pro 13" in ausgezeichnetem Zustand, geeignet für Arbeit und Studium.',
  'MacBook Pro 13" usato in ottime condizioni, adatto per lavoro e studio.',
  'Подержанный MacBook Pro 13" в отличном состоянии, подходит для работы и учёбы.',
  'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500',
  ARRAY['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500', 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500'],
  899.99, 
  2, 
  true, 
  (SELECT id FROM public.kategorije WHERE naziv = 'Elektronika' LIMIT 1),
  '{"procesor": "M1", "ram": "8GB", "disk": "256GB SSD", "leto": "2021", "stanje": "odlično", "javni_atributi": ["procesor", "ram", "disk", "leto", "stanje"]}',
  'novo',
  0,
  'macbook-pro-13-lap001'
);

-- Insert test coupons
INSERT INTO public.kuponi (koda, popust, veljavnost_od, veljavnost_do, aktivna, max_uporaba, trenutna_uporaba) VALUES
('NOVA2024', 10.00, now(), now() + interval '30 days', true, 100, 0),
('ZIMA50', 50.00, now(), now() + interval '60 days', true, 10, 0),
('TEST20', 20.00, now() - interval '10 days', now() + interval '5 days', true, 5, 2);