// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkftjzirmhsyvtodxzxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZnRqemlybWhzeXZ0b2R4enhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjAyMTYsImV4cCI6MjA2NTk5NjIxNn0.rX3LxN5eGm8AHN693W-3joRndUb8Rau1iHpvlAYtfpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);